title: "Alex Glaubach"
description: "Welcome to my personal website!"
baseurl: ""
url: "https://alexglaubach.com"
theme: minima

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

nav:
  - name: Home
    link: /
  - name: About
    link: /about/
  - name: Blog
    link: /blog/
